services:
  buildbot:
    image: buildbot/buildbot-master:master
    environment:
      BUILDBOT_REPO_URL: https://gitlab.freedesktop.org/poppler/poppler.git
      BUILDBOT_REPO_BRANCH: master
      BUILDBOT_CONFIG_DIR: config
      BUILDBOT_CONFIG_URL: https://github.com/buildbot/buildbot-docker-example-config/archive/master.tar.gz
      BUILDBOT_DB_URL: sqlite:///db/state.sqlite
      BUILDBOT_WORKER_PORT: 9989
      BUILDBOT_WEB_URL: http://127.0.0.1:8010/
      BUILDBOT_WEB_PORT: tcp:port=8010
      # default email settings for mailpit, see below
      # adjust to real SMTP service in production
      BUILDBOT_EMAIL_HOST: mailpit
      BUILDBOT_EMAIL_PORT: 1025
      BUILDBOT_EMAIL_USER: buildbot
      BUILDBOT_EMAIL_PASS: buildbot
      BUILDBOT_MAILNG_LIST: list@poppler.example.com
    volumes:
      - ./services/buildbot/master.cfg:/buildbot/master.cfg
      - ./sqlite/:/buildbot/db/

  worker:
    image: "poppler-ci-test1"
    environment:
      BUILDMASTER: buildbot
      BUILDMASTER_PORT: 9989
      WORKERNAME: poppler-worker
      WORKERPASS: pass
      WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST
    volumes:
      - ./refs:/buildbot/refs
      - ./outputs:/buildbot/outputs
    links:
      - buildbot

  flask:
    build: services/flask
    volumes:
      - ./services/flask:/buildbot/flask
      - ./refs:/buildbot/refs
      - ./outputs:/buildbot/outputs

  nginx-app:
    image: nginx
    volumes:
      - ./services/nginx-app/etc/nginx:/etc/nginx
      - ./refs:/public/refs
      - ./outputs:/public/outputs
    ports:
      - "8010:80"

  nginx-https:
    image: nginx
    env_file:
      - services/nginx-https/.env
    volumes:
      - ./services/nginx-https/etc/nginx:/etc/nginx
      - ./services/nginx-https/etc/letsencrypt:/etc/letsencrypt
      - ./services/nginx-https/var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  # uncomment for mail sending testing
  # mailpit:
  #   image: axllent/mailpit
  #   container_name: mailpit
  #   restart: unless-stopped
  #   volumes:
  #     - ./data:/data
  #   ports:
  #     - 8025:8025
  #     - 1025:1025
  #   environment:
  #     MP_MAX_MESSAGES: 5000
