services:
  buildbot:
    image: buildbot/buildbot-master:master
    env_file:
      - db.env
    environment:
      BUILDBOT_CONFIG_DIR: config
      BUILDBOT_CONFIG_URL: https://github.com/buildbot/buildbot-docker-example-config/archive/master.tar.gz
      BUILDBOT_WORKER_PORT: 9989
      BUILDBOT_WEB_URL: http://127.0.0.1:8010/
      BUILDBOT_WEB_PORT: tcp:port=8010
    volumes:
      - ../master.cfg:/buildbot/master.cfg
      - ../sqlite/:/buildbot/db/

  worker:
    image: "poppler-ci-test1"
    environment:
      BUILDMASTER: buildbot
      BUILDMASTER_PORT: 9989
      WORKERNAME: poppler-worker
      WORKERPASS: pass
      WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST
    volumes:
      - ../refs:/buildbot/refs
      - ../outputs:/buildbot/outputs
    links:
      - buildbot

  nginx_frontend:
    image: nginx
    env_file:
      - .env
    volumes:
      - ./etc/nginx-frontend:/etc/nginx
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  nginx_backend:
    image: nginx
    volumes:
      - ./etc/nginx-backend:/etc/nginx
      - ../refs:/public/refs
      - ../outputs:/public/outputs
    ports:
      - "8010:80"
